const https = require('https');
const fs = require('fs');
const path = require('path');

const FONTS_DIR = './fonts';
if (!fs.existsSync(FONTS_DIR)) fs.mkdirSync(FONTS_DIR);

const GOOGLE_FONTS_URL = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700&family=Inter:wght@300;400;500;600;700&display=swap';

// Use a modern Chrome UA so Google returns woff2 (smallest format)
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

function get(url, headers = {}) {
  return new Promise((resolve, reject) => {
    const opts = { headers: { 'User-Agent': UA, ...headers } };
    https.get(url, opts, res => {
      if (res.statusCode === 301 || res.statusCode === 302) {
        return get(res.headers.location, headers).then(resolve).catch(reject);
      }
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => resolve(Buffer.concat(chunks)));
      res.on('error', reject);
    }).on('error', reject);
  });
}

async function main() {
  console.log('Fetching Google Fonts CSS...');
  const css = (await get(GOOGLE_FONTS_URL)).toString('utf8');

  // Extract all @font-face blocks
  const faceBlocks = [...css.matchAll(/@font-face\s*\{[^}]+\}/g)].map(m => m[0]);
  console.log(`Found ${faceBlocks.length} @font-face blocks\n`);

  let localCss = '/* Self-hosted fonts — generated by download-fonts.js */\n\n';
  const downloaded = new Set();

  for (const block of faceBlocks) {
    const urlMatch = block.match(/url\(([^)]+)\)\s*format\('woff2'\)/);
    const familyMatch = block.match(/font-family:\s*'([^']+)'/);
    const weightMatch = block.match(/font-weight:\s*(\d+)/);
    const styleMatch = block.match(/font-style:\s*(\w+)/);
    const rangeMatch = block.match(/unicode-range:\s*([^;]+)/);

    if (!urlMatch) continue;

    const remoteUrl = urlMatch[1];
    const family = familyMatch ? familyMatch[1].replace(/\s+/g, '-') : 'font';
    const weight = weightMatch ? weightMatch[1] : '400';
    const style = styleMatch ? styleMatch[1] : 'normal';

    const fileName = `${family}-${weight}${style !== 'normal' ? '-' + style : ''}.woff2`;
    const filePath = path.join(FONTS_DIR, fileName);

    if (!downloaded.has(fileName)) {
      process.stdout.write(`  Downloading ${fileName}...`);
      const data = await get(remoteUrl);
      fs.writeFileSync(filePath, data);
      console.log(` ${Math.round(data.length / 1024)}KB`);
      downloaded.add(fileName);
    }

    // Build local @font-face block
    let localBlock = `@font-face {\n`;
    localBlock += `  font-family: '${familyMatch[1]}';\n`;
    localBlock += `  font-style: ${style};\n`;
    localBlock += `  font-weight: ${weight};\n`;
    localBlock += `  font-display: swap;\n`;
    localBlock += `  src: url('fonts/${fileName}') format('woff2');\n`;
    if (rangeMatch) localBlock += `  unicode-range: ${rangeMatch[1]};\n`;
    localBlock += `}\n\n`;

    localCss += localBlock;
  }

  fs.writeFileSync('./css/fonts.css', localCss);
  console.log(`\n✓ Written css/fonts.css with ${downloaded.size} font files`);
  console.log('✓ Font files saved to /fonts/');
}

main().catch(console.error);
